cond_cols: 3
cond_idx:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
include_time_in_cond: false
lr: 0.0001
pack_mode: y_window_cond_static
pack_select: random
pack_stride: 1
pack_win_len: 1
scheduler_cfg:
  factor: 0.1
  patience: 50
use_past_as_cond: false
y_cols: 6
y_idx:
- 0
